language: node_js
node_js:
  - 9

env:
  global:
    - TMPDIR=/tmp

addons:
  artifacts:
    paths:
      - './diff.html'
script:
- yarn 
- yarn build
- node bundlediff --path . --output "diff.html"

deploy:
  provider: surge
  project: .
  project: my-example-9876308.surge.sh
